name = "Lanis Adventures"
author = "Lani"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0fc0e4739ce436fa54402672ce2b8c423891643182f02517935f80b09fb588a"

[versions]
forge = "47.4.26"
minecraft = "1.20.1"
