name = "Lanis Adventures"
author = "Lani"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8794148d0d31b6287bfcd241e5877bab75fa6b1326114702df093f75692de97e"

[versions]
forge = "47.4.26"
minecraft = "1.20.1"
