name = "Lanis Adventures"
author = "Lani"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17629b69af8ce0d084c9d1c241e3767e52341f12aced02c1e0bad33f5b1ca976"

[versions]
forge = "47.4.26"
minecraft = "1.20.1"
